#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <functional>
#include <shared_mutex>
#include <cmath>
#include <algorithm>

// Conceptually includes the headers generated by your protoc compiler
// #include "property.pb.h"
// #include "search_request.pb.h"

namespace realest {
namespace hpc {

// Forward declarations for proto structures to allow this file to compile stand-alone
struct GeoLocation { double latitude; double longitude; };
struct Property { std::string id; GeoLocation location; /* ... */ };

/**
 * @class GeohashUtil
 * @brief Utility for encoding Lat/Lng into Base32 Geohash strings.
 * This effectively reduces 2D space into a 1D string prefix, allowing nearby 
 * properties to share the same prefix and thus land on the same worker node.
 */
class GeohashUtil {
public:
    static std::string encode(double lat, double lon, int precision = 6) {
        const char base32[] = "0123456789bcdefghjkmnpqrstuvwxyz";
        std::string hash;
        double lat_range[] = {-90.0, 90.0};
        double lon_range[] = {-180.0, 180.0};
        bool is_even = true;
        int bit = 0;
        int ch = 0;

        while (hash.size() < precision) {
            if (is_even) {
                double mid = (lon_range[0] + lon_range[1]) / 2.0;
                if (lon > mid) {
                    ch |= (1 << (4 - bit));
                    lon_range[0] = mid;
                } else {
                    lon_range[1] = mid;
                }
            } else {
                double mid = (lat_range[0] + lat_range[1]) / 2.0;
                if (lat > mid) {
                    ch |= (1 << (4 - bit));
                    lat_range[0] = mid;
                } else {
                    lat_range[1] = mid;
                }
            }
            is_even = !is_even;
            if (bit < 4) {
                bit++;
            } else {
                hash += base32[ch];
                bit = 0;
                ch = 0;
            }
        }
        return hash;
    }
};

/**
 * @class ConsistentHashRing
 * @brief Distributes Geohashes across worker nodes.
 * Uses virtual nodes (replicas) to ensure an even distribution of data.
 * When a node is added/removed, only `1/N` keys need to be remapped.
 */
class ConsistentHashRing {
public:
    explicit ConsistentHashRing(int virtual_nodes = 100) 
        : virtual_nodes_(virtual_nodes) {}

    void addNode(const std::string& node_address) {
        std::unique_lock<std::shared_mutex> lock(ring_mutex_);
        for (int i = 0; i < virtual_nodes_; ++i) {
            size_t hash = hasher_(node_address + "_vnode_" + std::to_string(i));
            ring_[hash] = node_address;
        }
    }

    void removeNode(const std::string& node_address) {
        std::unique_lock<std::shared_mutex> lock(ring_mutex_);
        for (int i = 0; i < virtual_nodes_; ++i) {
            size_t hash = hasher_(node_address + "_vnode_" + std::to_string(i));
            ring_.erase(hash);
        }
    }

    std::string getNode(const std::string& key) {
        std::shared_lock<std::shared_mutex> lock(ring_mutex_);
        if (ring_.empty()) return "";

        size_t hash = hasher_(key);
        auto it = ring_.lower_bound(hash);
        
        // Wrap around the ring if we went past the last node
        if (it == ring_.end()) {
            it = ring_.begin();
        }
        return it->second;
    }

private:
    std::map<size_t, std::string> ring_;
    std::hash<std::string> hasher_;
    int virtual_nodes_;
    // Using shared_mutex allows multiple threads to read (getNode) concurrently,
    // while write operations (addNode) require exclusive access.
    std::shared_mutex ring_mutex_; 
};

/**
 * @class ShardManager
 * @brief Core routing logic for the ingestion service.
 * Determines which gRPC worker node should receive a property or a search request.
 */
class ShardManager {
public:
    ShardManager() = default;

    // Registers an active worker node (e.g., "10.0.0.5:50051")
    void registerWorker(const std::string& address) {
        hash_ring_.addNode(address);
        std::cout << "[ShardManager] Registered Worker Node: " << address << "\n";
    }

    // Deregisters a node if health checks fail
    void deregisterWorker(const std::string& address) {
        hash_ring_.removeNode(address);
        std::cout << "[ShardManager] Removed Worker Node: " << address << "\n";
    }

    /**
     * @brief Routes an incoming property to the correct target node during Ingestion.
     * @param property The property to ingest.
     * @return The IP/Port address of the target worker node.
     */
    std::string routeIngestion(const Property& property) {
        // We use precision 4 for routing (roughly a ~40km x 20km bounding box).
        // This ensures close properties land on the same physical RAM.
        std::string geohash = GeohashUtil::encode(
            property.location.latitude, 
            property.location.longitude, 
            4
        );
        return hash_ring_.getNode(geohash);
    }

    /**
     * @brief Determines which node(s) need to be queried for a SearchRequest.
     * @param lat Center latitude of search
     * @param lon Center longitude of search
     * @param radius_meters The search radius (to determine if we cross shard boundaries)
     * @return A list of worker node addresses to broadcast the gRPC SearchRequest to.
     */
    std::vector<std::string> routeSearch(double lat, double lon, float radius_meters) {
        // In a fully robust implementation, if the radius overlaps multiple geohashes, 
        // you would calculate the neighboring geohashes and route to multiple nodes.
        // For Phase 1 demonstration, we route to the primary geohash node.
        
        std::string target_geohash = GeohashUtil::encode(lat, lon, 4);
        std::string primary_node = hash_ring_.getNode(target_geohash);
        
        std::vector<std::string> nodes;
        if (!primary_node.empty()) {
            nodes.push_back(primary_node);
        }
        
        // HPC Optimization Note: Phase 2 kernels run on the worker nodes.
        // By returning a vector here, the main.cc server can use `worker_pool.cc` 
        // to fire off parallel gRPC calls to multiple nodes if the radius requires it,
        // then aggregate the results.
        return nodes;
    }

private:
    ConsistentHashRing hash_ring_;
};

} // namespace hpc
} // namespace realest

/* // ============================================================================
// USAGE EXAMPLE (For main.cc)
// ============================================================================
// 
// #include "shard_manager.cc"
// 
// int main() {
//     realest::hpc::ShardManager manager;
// 
//     // Simulate registering Docker containers acting as worker nodes
//     manager.registerWorker("10.0.1.10:50051");
//     manager.registerWorker("10.0.1.11:50051");
//     manager.registerWorker("10.0.1.12:50051");
// 
//     // Ingest a property in downtown Austin, TX
//     realest::hpc::Property austin_home;
//     austin_home.id = "prop_99";
//     austin_home.location.latitude = 30.2672;
//     austin_home.location.longitude = -97.7431;
// 
//     std::string target_node = manager.routeIngestion(austin_home);
//     std::cout << "Route Austin Home to: " << target_node << "\n";
// 
//     // Execute a search query in a similar location
//     auto nodes_to_query = manager.routeSearch(30.2700, -97.7400, 5000.0);
//     std::cout << "Search broadcast to " << nodes_to_query.size() << " nodes.\n";
// 
//     return 0;
// }
*/